name: SvelteKit Check

on:
  push:
    branches: [main]

jobs:
  build:
    name: SvelteKit pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup BunJs
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

      - name: Build application
        run: bun run build
